### ISSUE TITLE
[16.0] web_responsive: wrong place of translation button for name fields

### ISSUE THREAD

**Issue by razvanioan** [OCA/web#2459]
## Module
web_responsive

## Describe the bug
If you enable translation for name fields (which are having oe_title class in the form), the translation button appears on the left side beneath the title instead of top right

## To Reproduce
**Affected versions**: `16.0.1.0.4`

1. activate translation for field which is wrapped in `oe_title` class div on the form

![image](https://user-images.githubusercontent.com/2914226/226273430-659ff0e2-16d0-47cd-a32b-e618a1a429a7.png)

**Expected behavior**
To have the translation button of the field inside the title on top right, but it's below left

![image](https://user-images.githubusercontent.com/2914226/226273800-3d6f837d-3b51-47f1-a6e9-7b130c5fb608.png)

**Additional context**
I think that the solution would be to filter out spans with class `o_field_translate` on the [web_responsive.scss#L171](https://github.com/OCA/web/blob/16.0/web_responsive/static/src/legacy/scss/web_responsive.scss#L171)

```scss
// Support for long title (with ellipsis)
.oe_title {
    .o_field_widget:not(.oe_inline) {
        display: block;
        span:not(.o_field_translate) {
            display: block;
            max-width: 100%;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
            width: initial;
            &:active {
                white-space: normal;
            }
        }
    }
}
```
